server:
  port: 8081
  shutdown: graceful

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  cloud:
    openfeign:
      okhttp:
        enabled: true
      autoconfiguration:
        jackson:
          enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql

  datasource:
    url: jdbc:mysql://chanhee-mysql.cxy4syck6vzh.ap-northeast-2.rds.amazonaws.com:3306/user?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}

  jwt:
    secret-key: ${JWT_SECRET_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/