server:
  port: 9090
  shutdown: graceful

spring:
  main:
    web-application-type: reactive

  jwt:
    secret-key: ${JWT_SECRET_KEY}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 디스커버리를 통해 동적으로 라우트 관리

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"