server:
  port: 9090

spring:
  main:
    web-application-type: reactive

  jwt:
    secret-key: ${JWT_SECRET_KEY}

  cloud:
    gateway:
      default-filters:
        - name: JwtAuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/