server:
  port: 8083

spring:
  application:
    name: payment-api

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  cloud:
    openfeign:
      okhttp:
        enabled: true
      autoconfiguration:
        jackson:
          enabled: true

  jpa:
    defer-datasource-initialization: true
    database: mysql
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/payment?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/